services:
  - type: web
    name: internauto-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_api_server.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
