services:
  - type: web
    name: internauto-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
